# Generated by Django 4.1.6 on 2023-03-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VOSTER', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alltools',
            new_name='HW',
        ),
    ]
