# Generated by Django 4.1.6 on 2023-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VOSTER', '0002_rename_alltools_hw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='il',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='sp',
            field=models.CharField(max_length=50),
        ),
    ]
