# Generated by Django 4.1.6 on 2023-03-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VOSTER', '0004_rename_tool_details_couse_remove_details_il_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw',
            name='start',
            field=models.DateTimeField(verbose_name='BEGAN FROM'),
        ),
    ]
